export enum ErrorCode {
  RATE_LIMIT_EXCEEDED = 10010,
  SOMETHING_WENT_WRONG = 50010,
  VALIDATION_ERROR = 40010,
  USER_ALREADY_EXISTS = 40020,
  USER_NOT_FOUND = 40030,
  INVALID_PASSWORD = 40040,
  INVALID_LOGIN = 40050,
  INVALID_PHONE = 40060,
  INVALID_EMAIL = 40070,
  RESTAURANT_ALREADY_EXISTS = 40080,
  UNAUTHORIZED = 40100,
  MISSING_OR_INVALID_TOKEN = 40110,
  TOKEN_EXPIRED = 40120,
  RESTAURANT_NOT_FOUND = 40410,
}

export enum HttpStatus {
  OK = 200,
  CREATED = 201,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  CONFLICT = 409,
  INTERNAL_SERVER_ERROR = 500,
  RATE_LIMIT_EXCEEDED = 429,
}

export enum ErrorMessage {
  RATE_LIMIT_EXCEEDED = "Rate limit exceeded",
  SOMETHING_WENT_WRONG = "Something went wrong",
  VALIDATION_ERROR = "Validation error",
  USER_ALREADY_EXISTS = "User already exists",
  INVALID_LOGIN = "Invalid login credentials",
  USER_NOT_FOUND = "User not found",
  INVALID_PASSWORD = "Password must be at least 8 characters long",
  INVALID_PHONE = "Invalid phone number format",
  MISSING_OR_INVALID_TOKEN = "Missing or invalid token",
  TOKEN_EXPIRED = "Token expired",
  UNAUTHORIZED = "Unauthorized",
  RESTAURANT_ALREADY_EXISTS = "Restaurant already exists",
  RESTAURANT_NOT_FOUND = "Restaurant not found",
}
